#!/bin/sh
[ ! -d "microReticulum_Firmware" ] && git clone https://github.com/attermann/microReticulum_Firmware
cd microReticulum_Firmware
git pull
#pio run -e native -t clean
pio run -e native -t fullclean
pio run -e native -t package
cp -p ./Release/*.zip ../.
cd ..
